# Generated by Django 5.1.2 on 2024-11-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentstandard_student_and_more'),
        ('tasks', '0003_remove_tasksstudents_task_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='studentStandard',
        ),
    ]
