# Generated by Django 5.1.2 on 2024-11-02 16:55

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
        ('mentors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('taskFile', models.FileField(upload_to='taskFiles/%Y/%B/%d')),
                ('taskImage', models.FileField(default=None, null=True, upload_to='taskImages/%Y/%B/%d')),
                ('description', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('assignees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.standards')),
                ('assignor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentors.mentors')),
            ],
        ),
        migrations.CreateModel(
            name='tasksStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completedDate', models.DateTimeField(auto_now_add=True)),
                ('submission', models.FileField(upload_to=tasks.models.student_submission_upload_path)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.students')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasks')),
            ],
        ),
    ]
