# Generated by Django 5.1.2 on 2024-11-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='dueDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
